<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="3" total="6" passed="1">
  <reporter-output>
    <line>
      <![CDATA[<a href="abcd.html">capture screenshot1</a>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="105" started-at="2017-09-15T10:53:28Z" finished-at="2017-09-15T10:53:28Z">
    <groups>
      <group name="low">
        <method signature="TestCase2.validateTitles()[pri:0, instance:testNG.TestCase2@3712b94]" name="validateTitles" class="testNG.TestCase2"/>
        <method signature="TestCase3.composeEmail()[pri:2, instance:testNG.TestCase3@704a52ec]" name="composeEmail" class="testNG.TestCase3"/>
      </group> <!-- low -->
      <group name="med">
        <method signature="TestCase3.doLogin()[pri:1, instance:testNG.TestCase3@704a52ec]" name="doLogin" class="testNG.TestCase3"/>
      </group> <!-- med -->
    </groups>
    <test name="LoginTest" duration-ms="17" started-at="2017-09-15T10:53:28Z" finished-at="2017-09-15T10:53:28Z">
    </test> <!-- LoginTest -->
    <test name="ValidateTitleTest" duration-ms="37" started-at="2017-09-15T10:53:28Z" finished-at="2017-09-15T10:53:28Z">
      <class name="testNG.TestCase2">
        <test-method status="FAIL" signature="validateTitles()[pri:0, instance:testNG.TestCase2@3712b94]" name="validateTitles" duration-ms="19" started-at="2017-09-15T06:53:28Z" finished-at="2017-09-15T06:53:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [yahoo] but found [gmail]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [yahoo] but found [gmail]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at testNG.TestCase2.validateTitles(TestCase2.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="abcd.html">capture screenshot1</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateTitles -->
      </class> <!-- testNG.TestCase2 -->
    </test> <!-- ValidateTitleTest -->
    <test name="DependencyTest" duration-ms="7" started-at="2017-09-15T10:53:28Z" finished-at="2017-09-15T10:53:28Z">
      <class name="testNG.TestCase3">
        <test-method status="PASS" signature="doLogin()[pri:1, instance:testNG.TestCase3@704a52ec]" name="doLogin" duration-ms="1" started-at="2017-09-15T06:53:28Z" finished-at="2017-09-15T06:53:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="SKIP" signature="composeEmail()[pri:2, instance:testNG.TestCase3@704a52ec]" name="composeEmail" duration-ms="1" started-at="2017-09-15T06:53:28Z" depends-on-methods="testNG.TestCase3.doLogin" finished-at="2017-09-15T06:53:28Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[skipping testcase]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: skipping testcase
	at testNG.TestCase3.composeEmail(TestCase3.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- composeEmail -->
      </class> <!-- testNG.TestCase3 -->
    </test> <!-- DependencyTest -->
  </suite> <!-- Suite -->
</testng-results>
